# Generated by Django 3.2.5 on 2021-07-11 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='author',
        ),
    ]
