# Generated by Django 3.2.5 on 2021-07-11 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0002_rename_name_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='store_name',
            new_name='name',
        ),
    ]
