# Generated by Django 3.2.5 on 2021-07-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0003_rename_store_name_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='desc',
        ),
    ]
